### ISSUE TITLE
allocation for split blocks

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/election-disag#1]
[ALARM](https://alarm-redist.github.io/posts/2021-08-10-census-2020/#technical-notes) used the [National Land Cover Database's](https://www.mrlc.gov/data?f%5B0%5D=year%3A2016) 2016 data to weight its allocation of votes.  The NLCD data distinguished between developed and undeveloped land, as well as the intensity of development.  For splitting blocks, the voter share of a split block is weighted by the land cover's intensity.

The [Esri Land Cover](https://livingatlas.arcgis.com/landcover/) has better data.  Not only is its data available on Census years, but its data also has finer granularity at 10-meter resolution (NLCD is at 30-meter).  How's your code addressing this issue?

**Comment by spencer-rdh** [comment]
Our disaggregation process does not split blocks. Instead, a block is associated with the precinct which the majority of its area is in. Working with the NLCD dataset to create the weights associated with each type of development (which is nuanced for each state, VEST has an article about this [here](https://dataverse.harvard.edu/file.xhtml?fileId=4513652&version=2.0)) was out of the scope for this project at this time.

**Comment by rootsmusic** [comment]
Ok @spencer-rdh, I think that you'll have problems with votes being allocated to blocks that don't have any VAP because you aren't splitting blocks.  In az_2020_disag.ipynb , is there a check for such errors?  Thanks.

**Comment by rootsmusic** [comment]
Ok @spencer-rdh, I think you'll have problems with more votes being allocated to blocks than VAP because you aren't splitting blocks. In az_2020_disag.ipynb , is there a check for such errors? Thanks.

**Comment by rdhlily** [comment]
Hi @rootsmusic , 

After blocks are assigned to a best-match precinct, the VAP of the precinct is calculated by summing all blocks associated with that precinct. Blocks are then normalized by their respective VAP (which we have modified to remove incarcerated persons) over the total VAP of the precinct. Votes are then allocated based on these  ratios, which sum to one therefore no votes are lost or added to the precinct and remain in tact, save the rounding.

We are working to get an updated AZ 2020 file up with updated results from the SOS, but in the meantime our key assumptions are listed in the readme (https://redistrictingdatahub.org/wp-content/uploads/2022/03/readme_az_20_block.txt) with the file available on our website. Hope this helps!

**Comment by rootsmusic** [comment]
Your website has [the shapefile](https://redistrictingdatahub.org/dataset/pennsylvania-block-pl-94-171-2020-official-prison-adjusted/) that's modified by PA's Redistricting Commission according to the final boundaries in the 2020 General Elections.  The Commission noted that its final boundaries correct "issues in the original 2020 data received from the Census Bureau", which was the data that VEST originally used for a base map (because the Commission hadn't released its final boundaries yet).  These corrected issues include split blocks.  Since your disaggregation is trying to avoid split blocks, would it be better to map the 2020 election results onto the Commission's shapefile?

**Comment by peter-redistricting-data-hub** [comment]
Yup, we're planning to disaggregate to that block file

**Comment by rootsmusic** [comment]
@peter-redistricting-data-hub, I support mapping onto the Redistricting Commission's shapefile because this choice eliminates geospatial errors and avoids disaggregation problems.  I think that your Data Analyst's challenge will be how to crosswalk with the Census' block assignment files to the Commission's "modified" VTDs (modified by the state after proposed VTDs had been submitted to the Census Bureau).
