### ISSUE TITLE
maup

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/election-disag#5]
@rdhlily   [disag2020.ipynb](https://github.com/nonpartisan-redistricting-datahub/cvap-processing/blob/main/disag2020.ipynb) disaggregated using [VEST's Census Block crosswalk data](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/T9VMJO&version=2.0), which was also used by ALARM's disaggregation code.  Why didn't you choose to use VEST's crosswalk in this repo's code?  Thanks.

**Comment by rdhlily** [comment]
@rootsmusic , we started disaggregating election results after the release of the 2020 Census data and geographies, so the crosswalk data was not necessary as we were then interested in the 2020 boundaries which we had direct access to.

**Comment by rootsmusic** [comment]
@rdhlily  I appreciate [your detailed explanation](https://github.com/nonpartisan-redistricting-datahub/election-disag/issues/3#issuecomment-1247273774), because I'm learning about disaggregation.  To conclude which assumption would produce less error in disaggregating 2018 election results, I should compare the 5-year estimate of CVAP against the 2020 VAP.

Except your first step, the rest of your explanation's list of steps seems to partly parallel VEST's methodology.  ALARM also used VEST's methodology to disaggregate [2018 election results to 2020 blocks](https://github.com/alarm-redist/census-2020/blob/main/vest-2020/pa/pa_2018_2020_vtd.csv), but I don't see the 2020 VAP in [ALARM's code](https://github.com/alarm-redist/census-2020/tree/main/R).  (ALARM didn't use maup though, which I don't understand because maup's documentation is inadequate.)  Does maup require you to input a population proxy (your choice being 2020 VAP) to disaggregate 2018 election results?  Thanks!

P.S. your explanation's last sentence is not wrong.  FYI though, the Census Bureau cautions (p. 13) in [_Understanding and Using American Community Survey Data_](https://www.census.gov/programs-surveys/acs/library/handbooks/general.html):
> Multiyear estimates should be labeled to indicate clearly the full period of time.
> Therefore, ACS estimates based on data collected from 2014–2018 should not be labeled '2016,' even though that is the midpoint of the 5-year period.

**Comment by rdhlily** [comment]
Yes, exactly, you can use any population variable you like. If you haven't already and are curious, I'd recommend checking out the [maup library Github](https://github.com/mggg/maup) for better understanding of their methodology.
