### ISSUE TITLE
Missing national code

### ISSUE THREAD

**Issue by rdhlily** [nonpartisan-redistricting-datahub/election-disag#9]
Just noticed the VA, and I assume all other states with disag, link to this repo, but the repo only contains individual states. Is the national processing script in another repo or local on your machine? Can you please upload it to this repo?

Thanks!

**Comment by spencer-rdh** [comment]
Yeah it's in a private repo. I can add a rough version to here. I modify it for each state/year slightly. could clean it up but don't really have time for that now
